'use client'

import { useState, useEffect } from 'react'
import { Copy, Check, X, MessageCircle, Share2, Send } from 'lucide-react'
import { format } from 'date-fns'
import { BalancedTeams } from '@/types'

interface WhatsAppExportProps {
  teams: BalancedTeams
  matchDate: Date
  opponent: string
  pitchName?: string | null
  sideSize: number
  balancePercentage: number
  bench?: { name: string; whatsappName?: string | null; primaryPosition: string }[]
  isOpen: boolean
  onClose: () => void
}

export function WhatsAppExport({
  teams,
  matchDate,
  opponent,
  pitchName,
  sideSize,
  balancePercentage,
  bench = [],
  isOpen,
  onClose,
}: WhatsAppExportProps) {
  const [copied, setCopied] = useState(false)
  const [previewMode, setPreviewMode] = useState<'formatted' | 'compact'>('formatted')

  useEffect(() => {
    if (copied) {
      const timer = setTimeout(() => setCopied(false), 3000)
      return () => clearTimeout(timer)
    }
  }, [copied])

  if (!isOpen) return null

  const formatDate = (date: Date) => {
    return format(new Date(date), 'EEE, d MMM @ h:mm a')
  }

  const generateWhatsAppMessage = (formatted: boolean) => {
    if (formatted) {
      return `⚽ SUNDAY LEAGUE MATCHDAY ⚽

📅 ${formatDate(matchDate)}
🆚 vs ${opponent}
${pitchName ? `📍 ${pitchName}` : ''}
👥 ${sideSize}v${sideSize}

━━━━━━━━━━━━━━━━━━━━━
🏆 WHITE TEAM
━━━━━━━━━━━━━━━━━━━━━
${teams.white.map((p, i) => `${i + 1}. ${p.whatsappName || p.name} (${p.primaryPosition})`).join('\n')}
Avg Rating: ${teams.whiteAvgRating}

━━━━━━━━━━━━━━━━━━━━━
🖤 BLACK TEAM
━━━━━━━━━━━━━━━━━━━━━
${teams.black.map((p, i) => `${i + 1}. ${p.whatsappName || p.name} (${p.primaryPosition})`).join('\n')}
Avg Rating: ${teams.blackAvgRating}
${bench.length > 0 ? `
━━━━━━━━━━━━━━━━━━━━━
📋 BENCH
━━━━━━━━━━━━━━━━━━━━━
${bench.map((p, i) => `${i + 1}. ${p.whatsappName || p.name} (${p.primaryPosition})`).join('\n')}` : ''}
━━━━━━━━━━━━━━━━━━━━━
⚖️ Balance: ${balancePercentage}%
━━━━━━━━━━━━━━━━━━━━━

Generated by Sunday League Manager`
    } else {
      return `⚽ SUNDAY LEAGUE
📅 ${formatDate(matchDate)} | vs ${opponent}
${pitchName ? `📍 ${pitchName}` : ''} | ${sideSize}v${sideSize}

🏆 WHITE: ${teams.white.map(p => p.whatsappName || p.name).join(', ')}
🖤 BLACK: ${teams.black.map(p => p.whatsappName || p.name).join(', ')}
${bench.length > 0 ? `📋 BENCH: ${bench.map(p => p.whatsappName || p.name).join(', ')}` : ''}
⚖️ Balance: ${balancePercentage}%`
    }
  }

  const handleCopy = async () => {
    const message = generateWhatsAppMessage(previewMode === 'formatted')
    await navigator.clipboard.writeText(message)
    setCopied(true)
  }

  const handleShare = async () => {
    const message = generateWhatsAppMessage(previewMode === 'formatted')
    const encodedMessage = encodeURIComponent(message)
    window.open(`https://wa.me/?text=${encodedMessage}`, '_blank')
  }

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50"
        onClick={onClose}
      />

      {/* Modal Panel */}
      <div className="fixed inset-4 md:inset-auto md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2 md:w-[600px] md:max-h-[85vh] bg-stadium-900 border-2 border-cyan-500/40 clip-corner z-50 overflow-hidden flex flex-col animate-slide-reveal">
        {/* Header */}
        <div className="relative bg-black/60 p-6 border-b border-cyan-500/30">
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-cyan-500 via-cyan-300 to-cyan-500" />

          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="p-2 bg-green-500/20 clip-corner-sm">
                <MessageCircle className="h-6 w-6 text-green-400" />
              </div>
              <div>
                <h2 className="text-xl font-black text-white uppercase tracking-wider">
                  WhatsApp Export
                </h2>
                <p className="text-sm text-gray-500">Copy or share with your squad</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-gray-500 hover:text-white hover:bg-stadium-800 transition-all clip-corner-sm"
            >
              <X className="h-6 w-6" />
            </button>
          </div>

          {/* Format Toggle */}
          <div className="flex space-x-2 mt-4">
            <button
              onClick={() => setPreviewMode('formatted')}
              className={`px-4 py-2 text-sm font-bold uppercase tracking-wider transition-all clip-corner-sm ${
                previewMode === 'formatted'
                  ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-400/40'
                  : 'bg-black/40 text-gray-500 border border-stadium-700 hover:text-white'
              }`}
            >
              Formatted
            </button>
            <button
              onClick={() => setPreviewMode('compact')}
              className={`px-4 py-2 text-sm font-bold uppercase tracking-wider transition-all clip-corner-sm ${
                previewMode === 'compact'
                  ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-400/40'
                  : 'bg-black/40 text-gray-500 border border-stadium-700 hover:text-white'
              }`}
            >
              Compact
            </button>
          </div>
        </div>

        {/* Preview */}
        <div className="flex-1 overflow-auto p-6">
          <div className="bg-black/60 border border-stadium-700/50 clip-corner-sm p-4">
            <pre className={`font-mono text-sm text-gray-300 whitespace-pre-wrap ${
              previewMode === 'compact' ? 'text-xs' : ''
            }`}>
              {generateWhatsAppMessage(previewMode === 'formatted')}
            </pre>
          </div>

          {/* Stats Summary */}
          <div className="grid grid-cols-3 gap-4 mt-6">
            <div className="text-center p-3 bg-black/40 border border-stadium-700/50 clip-corner-sm">
              <p className="text-2xl font-black text-white font-mono tabular-nums">
                {teams.white.length}
              </p>
              <p className="text-xs text-gray-500 uppercase tracking-widest">White</p>
            </div>
            <div className="text-center p-3 bg-black/40 border border-stadium-700/50 clip-corner-sm">
              <p className="text-2xl font-black text-cyan-400 font-mono tabular-nums">
                {balancePercentage}%
              </p>
              <p className="text-xs text-gray-500 uppercase tracking-widest">Balance</p>
            </div>
            <div className="text-center p-3 bg-black/40 border border-stadium-700/50 clip-corner-sm">
              <p className="text-2xl font-black text-gray-300 font-mono tabular-nums">
                {teams.black.length}
              </p>
              <p className="text-xs text-gray-500 uppercase tracking-widest">Black</p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 pt-4 border-t border-cyan-500/30 bg-black/40">
          <div className="flex space-x-4">
            <button
              onClick={handleCopy}
              className={`flex-1 btn-primary flex items-center justify-center space-x-2 ${
                copied ? 'bg-green-500 hover:bg-green-400' : ''
              }`}
            >
              {copied ? (
                <>
                  <Check className="h-5 w-5" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-5 w-5" />
                  <span>Copy to Clipboard</span>
                </>
              )}
            </button>
            <button
              onClick={handleShare}
              className="btn-secondary flex items-center justify-center space-x-2"
            >
              <Send className="h-5 w-5" />
              <span>Share via WhatsApp</span>
            </button>
          </div>
        </div>
      </div>
    </>
  )
}